apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $APP_NAME
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: $APP_NAME
    app.kubernetes.io/instance: $DEPLOY_TARGET
    managed-by: argocd
spec:
  project: default
  
  source:
    repoURL: $ARGOCD_REPO_URL
    targetRevision: $ARGOCD_TARGET_REVISION
    path: $ARGOCD_MANIFEST_PATH
    
    kustomize:
      commonLabels:
        environment: $DEPLOY_TARGET
        managed-by: argocd
      images:
        - $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG
  
  destination:
    server: $ARGOCD_DESTINATION_SERVER
    namespace: $NAMESPACE
  
  syncPolicy:
    automated:
      prune: $ARGOCD_AUTO_PRUNE
      selfHeal: $ARGOCD_AUTO_HEAL
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PruneLast=true
    
    retry:
      limit: $ARGOCD_SYNC_RETRY_LIMIT
      backoff:
        duration: $ARGOCD_RETRY_DURATION
        factor: $ARGOCD_RETRY_FACTOR
        maxDuration: $ARGOCD_RETRY_MAX_DURATION
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs