apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops
data:
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  NGINX_WORKER_PROCESSES: "auto"
  NGINX_WORKER_CONNECTIONS: "1024"