# Kubernetes Service manifest
apiVersion: v1
kind: Service
metadata:
  name: devops-webapp-service
  labels:
    app: devops-webapp
spec:
  type: NodePort
  selector:
    app: devops-webapp
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http