apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-app-config
  namespace: devops-app
  labels:
    app: devops-app
data:
  APP_NAME: devops-app
  APP_PORT: "3000"
  NODE_ENV: production
  LOG_LEVEL: info
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: devopsdb