apiVersion: v1
kind: Secret
metadata:
  name: devops-app-secrets
  namespace: devops-app
  labels:
    app: devops-app
type: Opaque
stringData:
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  API_KEY: "${API_KEY}"
  SESSION_SECRET: "${SESSION_SECRET}"