apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/YOUR_USERNAME/YOUR_REPO.git"
    targetRevision: master
    path: kubernetes/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: devops-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
